version: "3.4"
services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./media:/media
#    network: host
    network_mode: "host"
    environment:
      - PUID=1000         # UserID 
      - PGID=1000         # GroupID  
      - TZ=Europe/Berlin  # Timezone
    restart: "unless-stopped"
