name: "Jellyfin Docker Test"
on:
  push: 
  workflow_dispatch:
jobs:
  verify_network:
    runs-on: macos-11
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: "Navigate to jellyfin_docker"
      run: "cd jellyfin_docker"

    - name: Docker Setup
      uses: docker-practice/actions-setup-docker@1.0.8
      
    - name: Compose
      run: "sudo docker-compose up -d"

    - name: "Check if Jellyfin Server did Boot"
      uses: mydea/action-wait-for-api@v1
      with:
        url: "http://localhost:8096/System/Ping"
        expected-status: 200
